version: "2"
services:
  client:
    build: ./client
    ports:
      - 3333:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      network_backend:
        ipv4_address: 10.5.0.6

  executor:
    build: ./executor
    ports:
      - 8081:8081
    tty: true
    networks:
      network_backend:
        ipv4_address: 10.5.0.4
    # Production:
    #networks:
    #  - network_backend

  plagiarism:
    build: ./plagiarism
    ports:
      - 8082:8082
    tty: true
    networks:
      network_backend:
        ipv4_address: 10.5.0.5
    # Production:
    #networks:
    #  - network_backend

  server:
    image: maven:3.6.3-jdk-8
    command: mvn spring-boot:run
    ports:
      - 8080:8080
    volumes:
      - ./server:/usr/src/mymaven:rw
      #- ./server:/root/Submissions
    working_dir: /usr/src/mymaven
    networks:
      network_backend:
        ipv4_address: 10.5.0.3
    # Production:
    #networks:
    #  - network_backend

  database:
    image: mysql:5.7.31
    environment:
      MYSQL_DATABASE: db_codeflex
      MYSQL_USER: admin
      MYSQL_PASSWORD: spring-password!2018
      MYSQL_ROOT_PASSWORD: spring-password!2018
    volumes:
      - ~/databases/db_codeflex/data:/var/lib/mysql
    ports:
      - 3307:3306
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    networks:
      network_backend:
        ipv4_address: 10.5.0.2
    # Production
    #networks:
    #  - network_backend

networks:
  network_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
# Production
#networks:
#  network_backend:
#    driver: "bridge"
